{% set name = "dataeval" %}
{% set version = "0.74.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dataeval-{{ version }}.tar.gz
  sha256: bf72974a866b3342d30827092991bff61671fb32513d9d351bd28e86d0d659dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.9,<3.13
    - hdbscan >=0.8.36
    - numpy >1.24.3
    - pillow >=10.3.0
    - scipy >=1.10
    - scikit-learn >=1.5.0
    - tqdm *
    - python-xxhash >=3.3
  run_constrained:
    - matplotlib-base *
    - cudnn >=9.1.0.70
    - tensorflow >=2.16,<2.18
    - tensorflow_probability >=0.24,<0.25
    - tf-keras >=2.16,<2.18
    - pytorch >=2.2.0
    - torchvision >=0.17.0

test:
  imports:
    - dataeval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dataeval.ai/
  summary: DataEval provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aria-ml
