{% set name = "dataeval" %}
{% set version = "0.95.0" %}
{% set sha256 = "810d355ae0efc849a3693d45bb3d1441f5f26bd4e3b5fb787cfb96ef216c62ae" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dataeval-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - psutil >=7.0.0
    - lightgbm >=4
    - numba >=0.61.0
    - numpy >=1.24.2
    - polars >=1.0.0
    - python >={{ python_min }},<3.13
    - python-xxhash >=3.4
    - pytorch >=2.2.0
    - pydantic >=2.8
    - scipy >=1.10.0
    - scikit-learn >=1.5.0
    - typing_extensions >=4.12

test:
  imports:
    - dataeval
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://dataeval.ai/
  summary: DataEval provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aria-ml
