{% set name = "dataeval" %}
{% set version = "0.76.0" %}
{% set sha256 = "ede721714051a482b69a16a36507f3945e2da2a558580b6ce27bebd88957e223" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dataeval-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy >1.24.3
    - pillow >=10.3.0
    - python-xxhash >=3.3
    - pytorch >=2.2.0
    - requests *
    - scipy >=1.10
    - scikit-learn >=1.5.0
    - torchvision >=0.17.0
    - tqdm *
    - typing_extensions >=4.12

test:
  imports:
    - dataeval
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://dataeval.ai/
  summary: DataEval provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aria-ml
