{% set name = "dataeval" %}
{% set version = "0.71.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataeval-{{ version }}.tar.gz
  sha256: 09f6c6de621f60847e75f4374e081d9fe1d2c91d13417dec8a0872066430f240

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.9,<3.12
    - hdbscan >=0.8.36
    - numpy >1.24.3
    - pillow >=10.3.0
    - scipy >=1.10
    - scikit-learn >=1.5.0
    - tqdm *
    - python-xxhash >=3.3
  run_constrained:
    - matplotlib-base *
    - nvidia-cudnn-cu11 >=8.6.0.163
    - tensorflow >=2.14.1,<2.16
    - tensorflow-io-gcs-filesystem >=0.35.0,<0.37
    - tensorflow_probability >=0.22.1,<0.24
    - pytorch >=2.2.0
    - torchvision >=0.17.0

test:
  imports:
    - dataeval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dataeval.ai/
  summary: DataEval provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aria-ml
