{% set name = "dataeval" %}
{% set version = "0.94.0" %}
{% set sha256 = "e765cea18492ab32f6bd454c6aed265bab3ead05ec48d2e9ee5b471bc4bfa50b" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dataeval-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - psutil >=7.0.0
    - defusedxml >=0.7.1
    - fast_hdbscan ==0.2.0
    - lightgbm >=4
    - numba >=0.61.0
    - numpy >=1.24.2,<2.3
    - pandas >=2.0.0
    - pillow >=10.3.0
    - polars >=1.0.0
    - python >={{ python_min }},<3.13
    - python-xxhash >=3.4
    - pytorch >=2.2.0
    - scipy >=1.10.0
    - scikit-learn >=1.5.0
    - torchvision >=0.17.0
    - tqdm >=4.66
    - typing_extensions >=4.12

test:
  imports:
    - dataeval
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://dataeval.ai/
  summary: DataEval provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aria-ml
