{% set name = "dataeval" %}
{% set version = "1.0.0" %}
{% set sha256 = "d1cf694a0b67a60a96222cec788c3a1a490313ea75946097a4c6b43fbd912bab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dataeval-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - defusedxml >=0.7.1
    - fast_hdbscan 0.2.0
    - numba >=0.59.1
    - python >={{ python_min }},<3.13
    - numpy >=1.24.2
    - pillow >=10.3.0
    - python-xxhash >=3.3
    - pytorch >=2.2.0
    - requests
    - scipy >=1.10
    - scikit-learn >=1.5.0
    - torchvision >=0.17.0
    - tqdm
    - typing_extensions >=4.12

test:
  imports:
    - dataeval
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://dataeval.ai/
  summary: DataEval provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aria-ml
